In [2]:
def w_sum(input, weights):
    return sum( i*w for i, w in zip(input, weights, strict=True) )

def nn(input, weight):
    return w_sum(input, weight)

weights = [0.1, 0.2, 0]

toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

input = [toes[0], wlrec[0], nfans[0]]
# The more the input vector is alighed with the weight vector,
# the higher is the pred.
pred = nn(input, weights)
print(pred)

0.9800000000000001


In [1]:
def ew_mul(v1, v2):
    return [a * b for a, b in zip(v1, v2, strict=True)]

def ew_add(v1, v2):
    return [a+b for a, b in zip(v1, v2, strict=True)]

def vec_sum(v):
    return sum(v)

def vec_avg(v):
    assert len(v) > 0
    return sum(v)/len(v)

v1 = [1, 2, 3]
v2 = [0, 5, 2]

print(ew_mul(v1, v2))
print(ew_add(v1, v2))

print(vec_sum([1, 2, 3]))
print(vec_avg([1, 2, 3]))

[0, 10, 6]
[1, 7, 5]
6
2.0


Dot product is a measure of similarity between two vectors. The more the two vectors are pointing towards the same direction, the higher is their dot product.

In [4]:
import numpy as np
weights = np.array([0.1, 0.2, 0])

def nn(input, weights):
    return input.dot(weights)


toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

input = np.array([toes[0], wlrec[0], nfans[0]])
pred = nn(input, weights)
print(f"{pred=}")

pred=np.float64(0.9800000000000001)


In [11]:
def nn2(input, weight_matrix):
    return [
        sum(i * w for i, w in zip(input, weight)) for weight in weight_matrix
    ]

weight_matrix = [
    [0.1, 0.1, -0.3], # a row is for a single output
    [0.1, 0.2, 0.0],
    [0.0, 1.3, 0.1]
]

input = [toes[0], wlrec[0], nfans[0]]

preds = nn2(input, weight_matrix)
print(f"{preds=}")

preds=[0.5550000000000002, 0.9800000000000001, 0.9650000000000001]


In [24]:
# hidden layer outputs become inputs to output layer
def nn3(input, layers):
    hidden_layer_output = nn2(input, layers[0])
    return nn2(hidden_layer_output, layers[1])

hidden_layer = [
    [0.1, 0.2, -0.1],
    [-0.1, 0.1, 0.9],
    [0.1, 0.4, 0.1]
]

output_layer = [
    [0.3, 1.1, -0.3],
    [0.1, 0.2, 0.0],
    [0.0, 1.3, 0.1]
]

layers = [hidden_layer, output_layer]

input = [toes[0], wlrec[0], nfans[0]]
predictions = nn3(input, layers)
print(f"{predictions=}")

predictions=[0.21350000000000002, 0.14500000000000002, 0.5065]


In [27]:
import numpy as np

def nn4(input, layers):
    hidden_layer_outputs = input.dot(layers[0])
    return hidden_layer_outputs.dot(layers[1])

hidden_layer = np.array([
    [0.1, 0.2, -0.1],
    [-0.1, 0.1, 0.9],
    [0.1, 0.4, 0.1]
]).T

output_layer = np.array([
    [0.3, 1.1, -0.3],
    [0.1, 0.2, 0.0],
    [0.0, 1.3, 0.1]
]).T

layers = [hidden_layer, output_layer]

input = np.array([toes[0], wlrec[0], nfans[0]])
predictions = nn4(input, layers)
print(f"{predictions=}")

predictions=array([ 0.496,  1.256, -0.286])


In [28]:
a = np.array([0, 1, 2, 3])
b = np.array([4, 5, 6, 7])
print(a*b)

[ 0  5 12 21]


np.array is the common type for both vector and matrix.

In [36]:
h = np.zeros((5, 4))
h_t = np.zeros((5, 4)).T
i = np.zeros((5, 6))
# print(h.dot(i)) # ValueError: operands could not be broadcast together with shapes (5,4) (5,6) 
print(h_t.dot(i))

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
